#!/usr/bin/env bash
# Bash script that will display information about subdomains.
# Path: alx-system_engineering-devops/0x10-https_ssl/0-world_wide_web
subdomains_list=("www" "lb-01" "web-01" "web-02")
domain="$1"
subdomain="$2"
