#!/usr/bin/env bash
# A script that configures HAproxy in a load balancer
apt -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
echo -e "
frontend
        bind 80 ssl crt /etc/ssl/certs/haproxy.pem
        default_backend web-backend
        option forwardfor

backend web-backend
        balance roundrobin
        server 385252-web-01 34.229.49.127 check
        server 385252-web-02 54.173.120.12 check
        " >> /etc/haproxy/haproxy.cfg
service haproxy restart
