#!/usr/bin/env bash
#this script will display content of a file
filename="/etc/passwd"
content="$(cat $filename)"
start_char=":"
for i in $content; do
	part1=$(echo "$i" | cut -d "$start_char" -f 1)
	part2=$(echo "$i" | cut -d "$start_char" -f 3)
	part3=$(echo "$i" | cut -d "$start_char" -f 6)
	substring="$part1:$part2:$part3"
	echo "$substring"
done
