#!/usr/bin/env bash
#this program will print enfo about unix users

while read -r line; do
	username=$(echo "$line" | cut -d ":" -f 1)
	group_id=$(echo "$line" | cut -d ":" -f 4)
	home_directory=$(echo "$line" | cut -d ":" -f 6)
	command_shell=$(echo "$line" | cut -d ":" -f 7)
	user_id=$(echo "$line" | cut -d ":" -f 3)
	password=$(echo "$line" | cut -d ":" -f 2)
	username_info=$(echo "$line" | cut -d ":" -f 5)
	echo "The user $username is part of the $group_id gang, lives in $home_directory and rides $command_shell. $user_id's place is protected by the passcode $password, more info about the user here: $username_info"
done < "/etc/passwd"
