#!/usr/bin/env bash
#this script will display more occurency user in apache file log
awk '{ counts[$1" "$9]++ } END { for (value in counts) print counts[value], value }' "apache-access.log" | sort -nr
