#!/usr/bin/env bash
#this script will display info about school file.
school="school"
file="$("$PWD"/"$school")"
if [ -e "$file" ]; then
	if [ -s "$file" ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "$file" ]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
